spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orlp?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: unknown
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    host: smtp.gmail.com
    port: 587
    username: infolve.team@gmail.com
    password: unknown
app:
  jwt:
    header: Authentication
    secret: unknown
    expiration: 604800
    route:
      authentication:
        path: api/auth
        refresh: refresh
  reCaptcha:
    secretKey: unknown
    url: https://www.google.com/recaptcha/api/siteverify
  social:
    google:
      client-id: 109414995516-fftdn22fnpfdh80fgfsvpq1ht97hdkl5.apps.googleusercontent.com
      client-secret: unknown
      path: api/auth/google
    facebook:
      client-id: 439882899718340
      client-secret: unknown
      path: api/auth/facebook
  images:
    maxSize: 1048576
    userQuote: 10485760
  origin:
    url: http://localhost:3000
logging:
  file: orlp.log
  level:
    com.softserve.academy.spaced.repetition: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    springfox.documentation: ERROR
flyway:
  baseline-version: 1.1
  baseline-on-migrate: true
contactUsEmail: devdevdevdev@mailinator.com