spring:
  datasource:
    url: jdbc:mysql://localhost/orlp?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mail:
    host: smtp.gmail.com
    port: 587
    username: infolve.team@gmail.com
    password: z0935152261
app:
  jwt:
    header: Authentication
    secret: K&Mcq(\*cy(<9bUa)|E'(@]G$ao~'Vm1h@upwRWECrLvw~>M1J{26}g6ZAr;2}i
    expiration: 604800
    route:
      authentication:
        path: api/auth
        refresh: refresh
  reCaptcha:
    secretKey: 6LeS2ykUAAAAAPUUYX5h93VVp0cBhHB6c0PfMkRB
    url: https://www.google.com/recaptcha/api/siteverify
  social:
      google:
        client-id: 109414995516-fftdn22fnpfdh80fgfsvpq1ht97hdkl5.apps.googleusercontent.com
        client-secret: se5lxgYcg2xXeghejled31Ge
        path: api/auth/google
      facebook:
        client-id: 439882899718340
        client-secret: 94d6144f54723938f384ddb0a09daf81
        path: api/auth/facebook
  images:
    maxSize: 1048576
    userQuote: 10485760
  origin:
      url: http://localhost:3000
logging:
  file: orlp.log
  level:
    com.softserve.academy.spaced.repetition: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    springfox.documentation: ERROR
flyway:
  baseline-version: 1.1
  baseline-on-migrate: true