
spring:
  datasource:
    url: jdbc:mysql://localhost/orlp?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  social:
    google:
      client-id: 109414995516-fftdn22fnpfdh80fgfsvpq1ht97hdkl5.apps.googleusercontent.com
      client-secret: QyK5tYKCYN9KF40Lv--CWfY7
      path: api/auth/google
  mail:
    host: smtp.gmail.com
    port: 587
    username: sybez.market@gmail.com
    password: z0935152261

jwt:
  header: Authentication
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: api/auth
      refresh: refresh


